import { useEffect, useRef } from 'react';
import { AudioPlayer, createAudioPlayer, setAudioModeAsync } from 'expo-audio';
import { getProfile } from '../constants/profile';

// Benny's recorded lines — generated by scripts/generate-benny-voice.mjs
// using real neural TTS (Piper), never eSpeak or on-device system TTS, same
// "never synthesize at runtime" posture as hooks/usePhonics.ts. Currently
// SILENT PLACEHOLDERS (see that script's header comment): this sandbox
// can't reach the model-hosting sites needed to generate real audio, so the
// files exist (app builds/runs fine — Metro requires every require() path
// to resolve) but say nothing yet. Run that script locally once a voice
// model is downloaded and these become Benny's real voice with no code
// changes here.
//
// Only Emma's greeting is bundled right now — keyed by profile.childName so
// a different child's profile silently gets no greeting audio (still shows
// the on-screen text) rather than playing the wrong recorded name.
const GREETING_SOURCES: Record<string, ReturnType<typeof require>> = {
  emma: require('../assets/audio/benny/en/greeting.wav'),
};

const COUNT_SOURCES: Record<number, ReturnType<typeof require>> = {
  1: require('../assets/audio/benny/en/count_1.wav'),
  2: require('../assets/audio/benny/en/count_2.wav'),
  3: require('../assets/audio/benny/en/count_3.wav'),
  4: require('../assets/audio/benny/en/count_4.wav'),
  5: require('../assets/audio/benny/en/count_5.wav'),
};

const PRAISE_SOURCES: ReturnType<typeof require>[] = [
  require('../assets/audio/benny/en/praise_1.wav'),
  require('../assets/audio/benny/en/praise_2.wav'),
];

export default function useBennyVoice() {
  const greetingPlayer = useRef<AudioPlayer | null>(null);
  const countPlayers = useRef<Record<number, AudioPlayer>>({});
  const praisePlayers = useRef<AudioPlayer[]>([]);

  useEffect(() => {
    setAudioModeAsync({ playsInSilentMode: true }).catch(() => {});

    const nameKey = getProfile().childName.trim().toLowerCase();
    const greetingSource = GREETING_SOURCES[nameKey];
    if (greetingSource) {
      try {
        greetingPlayer.current = createAudioPlayer(greetingSource);
      } catch {
        // audio is a nice-to-have; never block the interaction on it
      }
    }

    for (const [n, source] of Object.entries(COUNT_SOURCES)) {
      try {
        countPlayers.current[Number(n)] = createAudioPlayer(source);
      } catch {
        // ignore
      }
    }

    for (const source of PRAISE_SOURCES) {
      try {
        praisePlayers.current.push(createAudioPlayer(source));
      } catch {
        // ignore
      }
    }

    return () => {
      [greetingPlayer.current, ...Object.values(countPlayers.current), ...praisePlayers.current].forEach(player => {
        try {
          player?.remove();
        } catch {
          // ignore
        }
      });
      greetingPlayer.current = null;
      countPlayers.current = {};
      praisePlayers.current = [];
    };
  }, []);

  async function playFrom(player: AudioPlayer | null | undefined) {
    if (!player) return;
    try {
      // seekTo is async on native (bridge call) — await it before play() so
      // a rapid re-tap doesn't start playback mid-seek.
      await player.seekTo(0);
      player.play();
    } catch {
      // ignore
    }
  }

  function playGreeting() {
    return playFrom(greetingPlayer.current);
  }

  function playCount(n: number) {
    return playFrom(countPlayers.current[n]);
  }

  function playPraise(random: () => number = Math.random) {
    const pool = praisePlayers.current;
    if (pool.length === 0) return Promise.resolve();
    return playFrom(pool[Math.floor(random() * pool.length)]);
  }

  return {
    playGreeting,
    playCount,
    playPraise,
  } as const;
}
