import { useEffect, useRef } from 'react';
import { AudioPlayer, createAudioPlayer, setAudioModeAsync } from 'expo-audio';
import { getProfile } from '../constants/profile';

// Benny's recorded lines — generated by scripts/generate-benny-voice.mjs
// using real neural TTS (Kokoro), never eSpeak or on-device system TTS,
// same "never synthesize at runtime" posture as hooks/usePhonics.ts.
// Currently SILENT PLACEHOLDERS (see that script's header comment): the
// files exist (app builds/runs fine — Metro requires every require() path
// to resolve) but say nothing yet until the generator is run with a real
// voice model.
//
// Only Emma's greeting is bundled right now — keyed by profile.childName so
// a different child's profile silently gets no greeting audio (still shows
// the on-screen text) rather than playing the wrong recorded name.
const GREETING_SOURCES: Record<string, ReturnType<typeof require>> = {
  emma: require('../assets/audio/benny/en/greeting.wav'),
};

const COUNT_SOURCES: Record<number, ReturnType<typeof require>> = {
  1: require('../assets/audio/benny/en/count_1.wav'),
  2: require('../assets/audio/benny/en/count_2.wav'),
  3: require('../assets/audio/benny/en/count_3.wav'),
  4: require('../assets/audio/benny/en/count_4.wav'),
  5: require('../assets/audio/benny/en/count_5.wav'),
};

// The performance loop's named lines (see hooks/useBennyChoreography.ts and
// useBennyPond.ts) — each played on demand by key via playLine.
export type BennyLineKey = 'perform_open_1' | 'perform_open_2' | 'perform_open_3' | 'perform_wow' | 'invite' | 'together';

const LINE_SOURCES: Record<BennyLineKey, ReturnType<typeof require>> = {
  perform_open_1: require('../assets/audio/benny/en/perform_open_1.wav'),
  perform_open_2: require('../assets/audio/benny/en/perform_open_2.wav'),
  perform_open_3: require('../assets/audio/benny/en/perform_open_3.wav'),
  perform_wow: require('../assets/audio/benny/en/perform_wow.wav'),
  invite: require('../assets/audio/benny/en/invite.wav'),
  together: require('../assets/audio/benny/en/together.wav'),
};

// The shared "we did it" celebration — a small rotating pool (picked
// randomly, same pattern as the old solo-praise lines) rather than a single
// fixed line, for a touch of variety.
const CELEBRATE_SOURCES: ReturnType<typeof require>[] = [
  require('../assets/audio/benny/en/celebrate_1.wav'),
  require('../assets/audio/benny/en/celebrate_2.wav'),
];

export default function useBennyVoice() {
  const greetingPlayer = useRef<AudioPlayer | null>(null);
  const countPlayers = useRef<Record<number, AudioPlayer>>({});
  const linePlayers = useRef<Partial<Record<BennyLineKey, AudioPlayer>>>({});
  const celebratePlayers = useRef<AudioPlayer[]>([]);

  useEffect(() => {
    setAudioModeAsync({ playsInSilentMode: true }).catch(() => {});

    const nameKey = getProfile().childName.trim().toLowerCase();
    const greetingSource = GREETING_SOURCES[nameKey];
    if (greetingSource) {
      try {
        greetingPlayer.current = createAudioPlayer(greetingSource);
      } catch {
        // audio is a nice-to-have; never block the interaction on it
      }
    }

    for (const [n, source] of Object.entries(COUNT_SOURCES)) {
      try {
        countPlayers.current[Number(n)] = createAudioPlayer(source);
      } catch {
        // ignore
      }
    }

    for (const [key, source] of Object.entries(LINE_SOURCES) as [BennyLineKey, ReturnType<typeof require>][]) {
      try {
        linePlayers.current[key] = createAudioPlayer(source);
      } catch {
        // ignore
      }
    }

    for (const source of CELEBRATE_SOURCES) {
      try {
        celebratePlayers.current.push(createAudioPlayer(source));
      } catch {
        // ignore
      }
    }

    return () => {
      [
        greetingPlayer.current,
        ...Object.values(countPlayers.current),
        ...Object.values(linePlayers.current),
        ...celebratePlayers.current,
      ].forEach(player => {
        try {
          player?.remove();
        } catch {
          // ignore
        }
      });
      greetingPlayer.current = null;
      countPlayers.current = {};
      linePlayers.current = {};
      celebratePlayers.current = [];
    };
  }, []);

  // Every Benny line is awaited by its caller expecting it to have actually
  // finished speaking before the next beat starts (see useBennyPond.ts's
  // perform/help/delight sequences) — but play() returns immediately, it
  // doesn't wait for playback to finish. Two problems followed once real
  // (non-instant) audio replaced the silent placeholders: sequential lines
  // overlapped (the next started as soon as play() *returned*, not when the
  // audio actually ended), and fixed-duration timers (e.g. the wait beat's
  // timeout) started counting down while a line was still speaking, eating
  // into — or skipping past — the time meant for her to tap.
  //
  // Fix: playFrom now resolves only once the player reports
  // didJustFinish, and every call is chained through one shared queue so
  // concurrent calls (e.g. two quick taps) play one at a time in order
  // instead of stacking on top of each other. A safety timeout guards
  // against a stalled/never-firing finish event so a bad file can never
  // wedge the whole interaction (this app's no-fail posture).
  const playChainRef = useRef<Promise<void>>(Promise.resolve());
  const PLAYBACK_FINISH_TIMEOUT_MS = 8000;

  function playOne(player: AudioPlayer): Promise<void> {
    return new Promise<void>(resolve => {
      let settled = false;
      let subscription: { remove: () => void } | undefined;
      const finish = () => {
        if (settled) return;
        settled = true;
        subscription?.remove();
        clearTimeout(timer);
        resolve();
      };
      const timer = setTimeout(finish, PLAYBACK_FINISH_TIMEOUT_MS);

      subscription = player.addListener('playbackStatusUpdate', status => {
        if (status.didJustFinish) finish();
      });

      (async () => {
        try {
          // seekTo is async on native (bridge call) — await it before
          // play() so a rapid re-tap doesn't start playback mid-seek.
          await player.seekTo(0);
          player.play();
        } catch {
          finish();
        }
      })();
    });
  }

  function playFrom(player: AudioPlayer | null | undefined): Promise<void> {
    if (!player) return Promise.resolve();
    const next = playChainRef.current.then(() => playOne(player));
    playChainRef.current = next.catch(() => {});
    return next;
  }

  function playGreeting() {
    return playFrom(greetingPlayer.current);
  }

  function playCount(n: number) {
    return playFrom(countPlayers.current[n]);
  }

  function playLine(key: BennyLineKey) {
    return playFrom(linePlayers.current[key]);
  }

  function playCelebrate(random: () => number = Math.random) {
    const pool = celebratePlayers.current;
    if (pool.length === 0) return Promise.resolve();
    return playFrom(pool[Math.floor(random() * pool.length)]);
  }

  return {
    playGreeting,
    playCount,
    playLine,
    playCelebrate,
  } as const;
}
